import type { Metadata } from "next";
import { Raleway, Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geist.variable, raleway.variable)}
    >
      <body>
        <div className="min-h-screen xl:px-32">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
